import 'dart:io';
import 'package:flutter/services.dart';
import 'package:image/image.dart' as img;
import 'package:path_provider/path_provider.dart';

class ImageUtils {
  static Future<String> generatePostImage(
      String imagePath, String postText) async {
    // 1. Decode images (original and logo)
    final originalImageFile = File(imagePath);
    final originalImageBytes = await originalImageFile.readAsBytes();
    final originalImage = img.decodeImage(originalImageBytes);
    if (originalImage == null) {
      throw Exception('Gagal memproses gambar');
    }

    final logoBytes = await rootBundle.load('lib/assets/img/logo-growell.png');
    final logoImage = img.decodeImage(logoBytes.buffer.asUint8List());
    if (logoImage == null) {
      throw Exception('Gagal memuat logo');
    }

    // 2. Prepare fonts and layout constants
    final lines = postText.split('\n');
    final titleFont = img.arial48;
    final textFont = img.arial24;
    const int textLineHeight = 30;
    const int padding = 40;
    const int footerHeight = 150;
    const title = 'Analisis Gizi';

    // Resize logo
    final resizedLogo = img.copyResize(logoImage, width: 150);

    // 3. Calculate dimensions
    final textHeight = (lines.length * textLineHeight) + 80; // Extra space for title
    final newHeight =
        originalImage.height + textHeight + footerHeight + (padding * 2);
    final newWidth = originalImage.width;

    // 4. Create canvas
    final newImage = img.Image(width: newWidth, height: newHeight);
    img.fill(newImage, color: img.ColorRgb8(245, 245, 245)); // Light grey background

    // 5. Draw main image with a border
    final imageY = padding;
    img.compositeImage(newImage, originalImage, dstX: 0, dstY: imageY);
    img.drawRect(
      newImage,
      x1: 0,
      y1: imageY,
      x2: newWidth - 1,
      y2: imageY + originalImage.height,
      color: img.ColorRgb8(0, 0, 0),
      thickness: 2,
    );

    // 6. Draw text section
    int currentY = imageY + originalImage.height + padding + 20;

    // Draw title
    final titleWidth = title.length * 24; // Estimate width
    img.drawString(
      newImage,
      title,
      font: titleFont,
      x: (newWidth - titleWidth) ~/ 2,
      y: currentY,
      color: img.ColorRgb8(0, 0, 0),
    );
    currentY += 60;

    // Draw nutrition lines
    for (final line in lines) {
      img.drawString(
        newImage,
        line,
        font: textFont,
        x: padding,
        y: currentY,
        color: img.ColorRgb8(50, 50, 50),
      );
      currentY += textLineHeight;
    }

    // 7. Draw footer
    final footerY = newHeight - footerHeight;
    img.drawLine(
      newImage,
      x1: padding,
      y1: footerY,
      x2: newWidth - padding,
      y2: footerY,
      color: img.ColorRgb8(200, 200, 200),
      thickness: 1,
    );

    // Draw centered logo
    final logoX = (newWidth - resizedLogo.width) ~/ 2;
    final logoY = footerY + 20;
    img.compositeImage(newImage, resizedLogo, dstX: logoX, dstY: logoY);

    // Draw centered text below logo
    const brandingText = 'Generated by Growell App';
    final brandingTextWidth = brandingText.length * 12; // Estimate width
    img.drawString(
      newImage,
      brandingText,
      font: textFont,
      x: (newWidth - brandingTextWidth) ~/ 2,
      y: logoY + resizedLogo.height + 10,
      color: img.ColorRgb8(150, 150, 150),
    );

    // 8. Encode and save
    final pngBytes = img.encodePng(newImage);
    final tempDir = await getTemporaryDirectory();
    final tempPath =
        '${tempDir.path}/growell_post_${DateTime.now().millisecondsSinceEpoch}.png';
    final tempFile = File(tempPath);
    await tempFile.writeAsBytes(pngBytes);

    return tempPath;
  }
}
