import 'dart:io';
import 'package:flutter/material.dart';

class PostCardWidget extends StatelessWidget {
  final String imagePath;
  final Map<String, double> nutritionData;

  const PostCardWidget({
    super.key,
    required this.imagePath,
    required this.nutritionData,
  });

  @override
  Widget build(BuildContext context) {
    return Card(
      elevation: 4.0,
      margin: const EdgeInsets.all(16.0),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(15.0),
      ),
      clipBehavior: Clip.antiAlias, // Important for rounded corners on the image
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Image.file(
            File(imagePath),
            width: double.infinity,
            fit: BoxFit.cover,
          ),
          Padding(
            padding: const EdgeInsets.all(12.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text(
                  'Analisis Gizi Makanan',
                  style: TextStyle(
                    fontSize: 14.0,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 6.0),
                ...nutritionData.entries.map((entry) {
                  return Text(
                    '${entry.key}: ${entry.value.toStringAsFixed(2)} g',
                    style: const TextStyle(fontSize: 10.0),
                  );
                }).toList(),
              ],
            ),
          ),
          const Divider(height: 1, thickness: 1),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 12.0, vertical: 6.0),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Image.asset('lib/assets/img/logo-growell.png', height: 18),
                const SizedBox(width: 6),
                const Text(
                  'Generated by Growell',
                  style: TextStyle(
                    fontSize: 9,
                    color: Colors.grey,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
