## ProGuard / R8 rules for Growell
## Added to address missing TensorFlow Lite GPU classes reported by R8.

# Suppress warnings for the GPU delegate factory options (generated by Gradle mapping)
-dontwarn org.tensorflow.lite.gpu.GpuDelegateFactory$Options

# Keep TensorFlow Lite classes used via reflection or native code
-keep class org.tensorflow.lite.** { *; }
-keep class org.tensorflow.lite.gpu.** { *; }
